name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  node_dir:  # dir of input repo
    description: 'Root folder of package.json relative to git repo'
    required: true
    default: '.'
  GITHUB_TOKEN:  # id of input
    description: 'GitHub Token'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
