on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install mocha
    - run: mocha -v
    - run: ./node_modules/.bin/mocha -v
    - name: Hello world action step
      id: hello
      uses: DesignrKnight/js-package-info@master
      with:
        who-to-greet: 'Awesome Person X'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
